# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

  displayName: 'Run a multi-line script'
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'IAT-Connection'
    subscriptionId: '3ec1895d-cf5d-471e-a6ae-b5fd233744ff'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'Zahra-Test'
    location: 'Germany West Central'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/Zahraazimy1/Zahra-Test/main/create_web_app/linkedStorageAccount.json'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPiplineTemplate'